
package de.video2brain.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebService", targetNamespace = "http://services.video2brain.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "doSomethingVeryLongLast", targetNamespace = "http://services.video2brain.de/", className = "de.video2brain.services.DoSomethingVeryLongLast")
    @ResponseWrapper(localName = "doSomethingVeryLongLastResponse", targetNamespace = "http://services.video2brain.de/", className = "de.video2brain.services.DoSomethingVeryLongLastResponse")
    public void doSomethingVeryLongLast(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://services.video2brain.de/", className = "de.video2brain.services.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://services.video2brain.de/", className = "de.video2brain.services.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
